server:
  port: 8080


logging.config: "classpath:logback.xml"

flex.bucket.uploader.url: "http://flex-bucket-uploader"
flex.reisetilskudd.backend.url: "http://flex-reisetilskudd-backend"

spring:
  main.banner-mode: 'off'
  profiles:
    active: default

allowed.origins: "localhost:3000,domain.nav.no"
