- basepath: isdialogmote
  serviceurlProperty: isdialogmote.url
  paths:
    get:
      - /api/v1/arbeidstaker/brev

- basepath: veilarboppfolging
  pathPrefix: /proxy/veilarboppfolging
  serviceurlProperty: pto.proxy.url
  extractAuthCookie: false
  paths:
    get:
      - /api/oppfolging
