- basepath: flex-bucket-uploader
  serviceurlProperty: flex.bucket.uploader.url
  paths:
    get:
      - /list
      - /kvittering/{blobName}
    post:
      - /opplasting

- basepath: flex-reisetilskudd-backend
  serviceurlProperty: flex.reisetilskudd.backend.url
  paths:
    get:
      - /api/v1/reisetilskudd
    put:
      - /api/v1/reisetilskudd/{id}/sporsmal/{sporsmalId}
    post:
      - /api/v1/reisetilskudd/{id}/send
      - /api/v1/reisetilskudd/{id}/avbryt
      - /api/v1/reisetilskudd/{id}/gjenapne
      - /api/v1/reisetilskudd/{id}/sporsmal/{sporsmalId}/svar
    delete:
      - /api/v1/reisetilskudd/{id}/sporsmal/{sporsmalId}/svar/{svarId}


- basepath: spinnsyn-backend
  serviceurlProperty: spinnsyn.backend.url
  paths:
    get:
      - /api/v1/vedtak
      - /api/v1/vedtak/{id}
    post:
      - /api/v1/vedtak/{id}/les

- basepath: syfosoknad
  serviceurlProperty: syfosoknad.url
  apiGwKeyProperty: service.gateway.key
  pathRewrite: false
  paths:
    get:
      - /api/arbeidsgiver/soknader
      - /api/soknader
      - /api/sykeforloep
      - /api/sykmeldinger/{sykmeldingId}/actions/behandlet
      - /api/sykmeldinger/{sykmeldingId}/actions/erUtenforVentetid
      - /api/sykmeldinger/{sykmeldingId}/soknader
      - /api/syfosyketilfelle/39ukersvarsel
    post:
      - /api/opprettSoknadUtland
      - /api/soknader/{id}/send
      - /api/soknader/{id}/ettersendTilNav
      - /api/soknader/{id}/ettersendTilArbeidsgiver
      - /api/soknader/{id}/avbryt
      - /api/soknader/{id}/gjenapne
      - /api/soknader/{id}/korriger
      - /api/soknader/{id}/mottaker
      - /api/soknader/{id}/finnMottaker
      - /api/sykmeldinger/{sykmeldingId}/actions/skalOppretteSoknad
    put:
      - /api/soknader/{id}/sporsmal/{sporsmalId}
