- basepath: flex-bucket-uploader
  serviceurlProperty: flex.bucket.uploader.url
  paths:
    get:
      - /kvittering/{blobName}
    post:
      - /opplasting

- basepath: spinnsyn-backend
  serviceurlProperty: spinnsyn.backend.url
  paths:
    get:
      - /api/v2/vedtak
    post:
      - /api/v2/vedtak/{id}/les

- basepath: isdialogmote
  serviceurlProperty: isdialogmote.url
  paths:
    get:
      - /api/v1/arbeidstaker/brev

- basepath: flex-syketilfelle
  serviceurlProperty: flex.syketilfelle.url
  paths:
    get:
      - /api/bruker/v1/sykeforloep
      - /api/bruker/v1/ventetid/{sykmeldingId}/erUtenforVentetid

- basepath: syfosoknad
  serviceurlProperty: syfosoknad.url
  apiGwKeyProperty: service.gateway.key
  pathRewrite: false
  paths:
    get:
      - /api/arbeidsgiver/soknader
      - /api/soknader
      - /api/sykeforloep
      - /api/sykmeldinger/{sykmeldingId}/actions/behandlet
      - /api/sykmeldinger/{sykmeldingId}/actions/behandlet-detaljert
      - /api/sykmeldinger/{sykmeldingId}/actions/erUtenforVentetid
      - /api/sykmeldinger/{sykmeldingId}/actions/v2/erUtenforVentetid
      - /api/sykmeldinger/{sykmeldingId}/soknader
      - /api/syfosyketilfelle/39ukersvarsel
    post:
      - /api/opprettSoknadUtland
      - /api/soknader/{id}/send
      - /api/soknader/{id}/ettersendTilNav
      - /api/soknader/{id}/ettersendTilArbeidsgiver
      - /api/soknader/{id}/avbryt
      - /api/soknader/{id}/gjenapne
      - /api/soknader/{id}/korriger
      - /api/soknader/{id}/mottaker
      - /api/soknader/{id}/finnMottaker
      - /api/soknader/{id}/sporsmal/{sporsmalId}/svar
      - /api/sykmeldinger/{sykmeldingId}/actions/skalOppretteSoknad
    delete:
      - /api/soknader/{id}/sporsmal/{sporsmalId}/svar/{svarId}
    put:
      - /api/soknader/{id}/sporsmal/{sporsmalId}

- basepath: veilarboppfolging
  pathPrefix: /proxy/veilarboppfolging
  serviceurlProperty: pto.proxy.url
  extractAuthCookie: false
  paths:
    get:
      - /api/oppfolging
